






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace MobileFirst.Sample.Model
{

public partial interface IGlassBase {

		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.DisplayName)]
		string DisplayName { get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
		Guid TemplateId{ get; }

		[SitecoreField(FieldId = "{BA3F86A2-4A1C-4D78-B63D-91C2779C1B5E}")]
        int SortOrder { get; }

		[SitecoreField(FieldId = "{86FE4F77-4D9A-4EC3-9ED9-263D03BD1965}")]
        DateTime Publish { get; }

		[SitecoreField(FieldId = "{F1A1FE9E-A60C-4DDB-A3A0-BB5B29FE732E}")]
        string Layout { get; }
		
	    [SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get; }

}

public abstract partial class GlassBase : IGlassBase {

		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.DisplayName)]
		public virtual string DisplayName{ get; set; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
		public virtual Guid TemplateId{ get; private set;}

		[SitecoreField(FieldId = "{BA3F86A2-4A1C-4D78-B63D-91C2779C1B5E}")]
        public virtual int SortOrder { get; private set; }

		[SitecoreField(FieldId = "{86FE4F77-4D9A-4EC3-9ED9-263D03BD1965}")]
        public virtual DateTime Publish { get; private set; }

		[SitecoreField(FieldId = "{F1A1FE9E-A60C-4DDB-A3A0-BB5B29FE732E}")]
         public virtual string Layout { get; private set;}

	    [SitecoreInfo(SitecoreInfoType.Name)]
        public virtual string Name { get; private set; }
}
}
namespace MobileFirst.Sample.Model.sitecore.templates.Feature
{


 	/// <summary>
	/// ISample Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Sample</para>	
	/// <para>ID: 5771bf84-1ba0-4403-a35b-42949672ebca</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISampleConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISample : IGlassBase 
	{
			
					/// <summary>
					/// The Sample Text field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 43fff124-d4db-48ab-aadb-5bc2d153d325</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISampleConstants.Sample_TextFieldName)]
					string Sample_Text  {get; set;}
			
			
	}


	public static partial class ISampleConstants{

			public const string TemplateIdString = "5771bf84-1ba0-4403-a35b-42949672ebca";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Sample";

		
			
			public static readonly ID Sample_TextFieldId = new ID("43fff124-d4db-48ab-aadb-5bc2d153d325");
			public const string Sample_TextFieldName = "Sample Text";
			
			

	}

	
	/// <summary>
	/// Sample
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Sample</para>	
	/// <para>ID: 5771bf84-1ba0-4403-a35b-42949672ebca</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISampleConstants.TemplateIdString)] //, Cachable = true
	public partial class Sample  : GlassBase, ISample 
	{
	   
		
				/// <summary>
				/// The Sample Text field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 43fff124-d4db-48ab-aadb-5bc2d153d325</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISampleConstants.Sample_TextFieldName)]
				public virtual string Sample_Text  {get; set;}
					
			
	}

}
